-- ============================================
-- SCHEMA FOR MediHealth appointments table
-- This file describes the structure of the table
-- used by the MediHealth Appointments project.
-- ============================================

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        -- Unique ID for each appointment (auto generated)

    patient_name TEXT NOT NULL,
        -- Name of the patient (text input from the form)

    appointment_date DATE NOT NULL,
        -- Date of the appointment (date input)

    notes TEXT,
        -- Optional notes about the appointment

    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
        -- Time and date that the row was created
);

-- Notes for students:
-- - You create this table once in Supabase.
-- - The column names must match the JavaScript body object.
-- - id and created_at are handled automatically by the database.
